---
title: "analysis"
author: "Daniel Ward"
date: "29/04/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Imports
```{r}
library(tidyverse)
theme_set(theme_bw())
```


## Read in results
```{r}
df = read_csv("results/general_performance.csv")
df = select(df, -X1)
df$algorithm[df$algorithm == "rula"] = "RULA"
df$algorithm[df$algorithm == "rwm"] = "RW-Metropolis"
df
```


## Run times
We can compare the run times of the two algorithms:
```{r}
ggplot(df, aes(y = run_time, x = task, col = algorithm)) +
  geom_point() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  labs(y = "run time / s") +
  lims(y = c(0,2000))
ggsave("plots/run_times.png")
```


## Effective sample sizes
We can compare the effective sample sizes of the two algorithms. The lines show
the max and min.

```{r}
ggplot(df, aes(x = task, y = mean_ess, col = algorithm)) +
  geom_point() +
  geom_pointrange(aes(ymin = min_ess, ymax = max_ess), alpha = 0.5) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  ylab("mean ESS")
ggsave("plots/ess.png")
```

## Classification accuracy
```{r}
df %>%
  pivot_longer(cols = c(c2st_all, c2st_thinned), names_to = "thinned", values_to = "c2st") %>%
  mutate(thinned = case_when(
    thinned == "c2st_thinned" ~ "Thinned",
    thinned == "c2st_all" ~ "All samples"
    )) %>%
  ggplot(aes(x = task, y = c2st, col = algorithm), names_to = c("l")) +
  facet_wrap(~thinned) +
  geom_point() + 
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  lims(y = c(0.5,1))
ggsave("plots/c2st.png")
```


## Acceptance probabilities
```{r}
df %>%
  filter(algorithm == "RW-Metropolis") %>%
  ggplot(aes(x = task, y = acceptance_rate)) +
  geom_point() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  lims(y = c(0, 0.6))

ggsave("plots/acceptance_rates.png")
```

